controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_create_project:
    path: /create-project
    controller: App\Controller\ApiController::randomName
